# Generated by Django 5.0.8 on 2025-04-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_attend_delete_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('Employee', 'Employee'), ('employer', 'Employer'), ('manager', 'Manager'), ('intern', 'Intern'), ('admin', 'Admin')], default='', max_length=10),
        ),
    ]
