# Generated by Django 4.2.7 on 2025-05-06 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_goal_attachment_goal_priority_taskcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('employee', 'Employee'), ('employer', 'Employer'), ('intern', 'Intern'), ('superadmin', 'Superadmin'), ('admin', 'Admin')], default='', max_length=10),
        ),
    ]
