# Generated by Django 4.2.7 on 2025-05-20 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_goal_tags_workspace_goal_workspace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('employer', 'Employer'), ('intern', 'Intern'), ('superadmin', 'Superadmin'), ('admin', 'Admin')], default='', max_length=10),
        ),
    ]
